# docker-compose.yml - Développement (SQLite)

services:
  # Application MPPEEP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mppeep-app-dev
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=sqlite:///./data/mppeep.db
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production-minimum-32-chars}
      - DEBUG=True
      - APP_NAME=MPPEEP Dashboard
      - APP_VERSION=1.0.0
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    volumes:
      # Code source (hot reload)
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
      # Données persistantes
      - mppeep-dev-data:/app/data
      - mppeep-dev-logs:/app/logs
      - mppeep-dev-uploads:/app/static/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
    restart: unless-stopped
    networks:
      - mppeep-dev-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9000/api/v1/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mppeep-dev-data:
    driver: local
  mppeep-dev-logs:
    driver: local
  mppeep-dev-uploads:
    driver: local

networks:
  mppeep-dev-network:
    driver: bridge
